%include "core/entry.asm"
%include "core/symbols.asm"
%include "core/arch.asm"
%include "core/serial.asm"
%include "core/framebuffer.asm"
%include "core/rng.asm"
%include "core/debug.asm"
%include "core/mm.asm"
